// ./redux/artist/artistActionTypes.js

export const UPDATE_SONG_REQUEST = 'UPDATE_SONG_REQUEST';
export const UPDATE_SONG_SUCCESS = 'UPDATE_SONG_SUCCESS';
export const UPDATE_SONG_FAILURE = 'UPDATE_SONG_FAILURE';

export const ADD_SONG_REQUEST = 'ADD_SONG_REQUEST';
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS';
export const ADD_SONG_FAILURE = 'ADD_SONG_FAILURE';

export const FETCH_FOLLOWING_REQUEST = 'FETCH_FOLLOWING_REQUEST';
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWING_SUCCESS';
export const FETCH_FOLLOWING_FAILURE = 'FETCH_FOLLOWING_FAILURE';

export const FETCH_CREATED_SONGS_REQUEST = 'FETCH_CREATED_SONGS_REQUEST';
export const FETCH_CREATED_SONGS_SUCCESS = 'FETCH_CREATED_SONGS_SUCCESS';
export const FETCH_CREATED_SONGS_FAILURE = 'FETCH_CREATED_SONGS_FAILURE';