// artistActionTypes.js

export const UPDATE_SONG_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_SONG_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_SONG_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const ADD_SONG_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const ADD_SONG_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const ADD_SONG_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const FETCH_FOLLOWING_REQUEST = 'FETCH_FOLLOWED_ARTISTS_REQUEST';
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWED_ARTISTS_SUCCESS';
export const FETCH_FOLLOWING_FAILURE = 'FETCH_FOLLOWED_ARTISTS_FAILURE';

export const FETCH_CREATED_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_CREATED_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_CREATED_SONGS_FAILURE = 'FETCH_SONGS_FAILURE';
