// ./redux/artist/artistActionTypes.js

export const FETCH_FOLLOWING_REQUEST = 'FETCH_FOLLOWING_REQUEST';
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWING_SUCCESS';
export const FETCH_FOLLOWING_FAILURE = 'FETCH_FOLLOWING_FAILURE';

export const FETCH_CREATED_SONGS_REQUEST = 'FETCH_CREATED_SONGS_REQUEST';
export const FETCH_CREATED_SONGS_SUCCESS = 'FETCH_CREATED_SONGS_SUCCESS';
export const FETCH_CREATED_SONGS_FAILURE = 'FETCH_CREATED_SONGS_FAILURE';

export const ADD_SONG_REQUEST = 'ADD_SONG_REQUEST';
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS';
export const ADD_SONG_FAILURE = 'ADD_SONG_FAILURE';

export const EDIT_SONG_REQUEST = 'EDIT_SONG_REQUEST';
export const EDIT_SONG_SUCCESS = 'EDIT_SONG_SUCCESS';
export const EDIT_SONG_FAILURE = 'EDIT_SONG_FAILURE';

export const DELETE_SONG_REQUEST = 'DELETE_SONG_REQUEST';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAILURE = 'DELETE_SONG_FAILURE';