// userActionTypes.js

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const LIKE_SONG_REQUEST = 'LIKE_SONG_REQUEST';
export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS';
export const LIKE_SONG_FAILURE = 'LIKE_SONG_FAILURE';

export const FOLLOW_ARTIST_REQUEST = 'FOLLOW_ARTIST_REQUEST';
export const FOLLOW_ARTIST_SUCCESS = 'FOLLOW_ARTIST_SUCCESS';
export const FOLLOW_ARTIST_FAILURE = 'FOLLOW_ARTIST_FAILURE';

export const FETCH_LIKED_SONGS_REQUEST = 'FETCH_LIKED_SONGS_REQUEST';
export const FETCH_LIKED_SONGS_SUCCESS = 'FETCH_LIKED_SONGS_SUCCESS';
export const FETCH_LIKED_SONGS_FAILURE = 'FETCH_LIKED_SONGS_FAILURE';

export const FETCH_FOLLOWED_ARTISTS_REQUEST = 'FETCH_FOLLOWED_ARTISTS_REQUEST';
export const FETCH_FOLLOWED_ARTISTS_SUCCESS = 'FETCH_FOLLOWED_ARTISTS_SUCCESS';
export const FETCH_FOLLOWED_ARTISTS_FAILURE = 'FETCH_FOLLOWED_ARTISTS_FAILURE';

export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_FAILURE = 'FETCH_SONGS_FAILURE';

export const FETCH_ARTISTS_REQUEST = 'FETCH_ARTISTS_REQUEST';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAILURE = 'FETCH_ARTISTS_FAILURE';
